os: linux
dist: bionic
language: csharp
dotnet: 5.0.101

install:
  - dotnet restore src/DbCtl.sln

script:
  - dotnet test src/DbCtl.Tests/DbCtl.Tests.csproj
  - dotnet test src/DbCtl.Tests/DbCtl.SqlServer.Tests.csproj
  - dotnet build -c Release src/DbCtl.sln

before_deploy:
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
  - dotnet publish -c Release src/DbCtl/DbCtl.csproj -p:PublishProfile=FolderProfile
  - zip -r DbCtl-$TRAVIS_TAG.zip src/DbCtl/bin/Release/net5.0/publish/
  
deploy:
  provider: releases
  token: $GITHUB_API_KEY
  file: DbCtl-$TRAVIS_TAG.zip
  skip_cleanup: true
  on:
    branch: main